language: node_js
node_js:
  - "10"

before_install:
  - npm i -g npm
  - sudo apt-get install libatlas-base-dev

# Cache node dependencies
cache:
  directories:
    - node_modules
    - bower_components
